/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type Error = {
  data?: Record<string, any> | Record<string, any>[] | null;
  error: {
    status?: number;
    name?: string;
    message?: string;
    details?: Record<string, any>;
  };
};

export type CategoryRequest = {
  data: {
    Name?: string;
    events?: (number | string)[];
  };
};

export type CategoryListResponseDataItem = {
  id?: number;
  attributes?: Category;
};

export type CategoryListResponse = {
  data?: CategoryListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type Category = {
  Name?: string;
  events?: {
    data?: {
      id?: number;
      attributes?: {
        /**
         * @pattern ^\d*$
         * @example 123456789
         */
        E_ID?: string;
        /**
         * @pattern ^\d*$
         * @example 123456789
         */
        eventId?: string;
        /**
         * @pattern ^\d*$
         * @example 123456789
         */
        terminId?: string;
        title?: string;
        description?: string;
        coords?: void;
        /**
         * @format date-time
         */
        startDate?: string;
        /**
         * @format date-time
         */
        endDate?: string;
        urls?: void;
        categories?: {
          data?: {
            id?: number;
            attributes?: {
              Name?: string;
              events?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {
                    firstname?: string;
                    lastname?: string;
                    username?: string;
                    /**
                     * @format email
                     */
                    email?: string;
                    resetPasswordToken?: string;
                    registrationToken?: string;
                    isActive?: boolean;
                    roles?: {
                      data?: {
                        id?: number;
                        attributes?: {
                          name?: string;
                          code?: string;
                          description?: string;
                          users?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            }[];
                          };
                          permissions?: {
                            data?: {
                              id?: number;
                              attributes?: {
                                action?: string;
                                actionParameters?: void;
                                subject?: string;
                                properties?: void;
                                conditions?: void;
                                role?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                                /**
                                 * @format date-time
                                 */
                                createdAt?: string;
                                /**
                                 * @format date-time
                                 */
                                updatedAt?: string;
                                createdBy?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                                updatedBy?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                              };
                            }[];
                          };
                          /**
                           * @format date-time
                           */
                          createdAt?: string;
                          /**
                           * @format date-time
                           */
                          updatedAt?: string;
                          createdBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          updatedBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                        };
                      }[];
                    };
                    blocked?: boolean;
                    preferedLanguage?: string;
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    }[];
  };
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
};

export type CategoryResponseDataObject = {
  id?: number;
  attributes?: Category;
};

export type CategoryResponse = {
  data?: CategoryResponseDataObject;
  meta?: Record<string, any>;
};

export type ConfigRequest = {
  data: {
    config?: void;
  };
};

export type ConfigListResponseDataItem = {
  id?: number;
  attributes?: Config;
};

export type ConfigListResponse = {
  data?: ConfigListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type Config = {
  config?: void;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {
        firstname?: string;
        lastname?: string;
        username?: string;
        /**
         * @format email
         */
        email?: string;
        resetPasswordToken?: string;
        registrationToken?: string;
        isActive?: boolean;
        roles?: {
          data?: {
            id?: number;
            attributes?: {
              name?: string;
              code?: string;
              description?: string;
              users?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              permissions?: {
                data?: {
                  id?: number;
                  attributes?: {
                    action?: string;
                    actionParameters?: void;
                    subject?: string;
                    properties?: void;
                    conditions?: void;
                    role?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        blocked?: boolean;
        preferedLanguage?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
};

export type ConfigResponseDataObject = {
  id?: number;
  attributes?: Config;
};

export type ConfigResponse = {
  data?: ConfigResponseDataObject;
  meta?: Record<string, any>;
};

export type EventRequest = {
  data: {
    /**
     * @pattern ^\d*$
     * @example 123456789
     */
    E_ID?: string;
    /**
     * @pattern ^\d*$
     * @example 123456789
     */
    eventId?: string;
    /**
     * @pattern ^\d*$
     * @example 123456789
     */
    terminId?: string;
    title?: string;
    description?: string;
    coords?: void;
    /**
     * @format date-time
     */
    startDate?: string;
    /**
     * @format date-time
     */
    endDate?: string;
    urls?: void;
    categories?: (number | string)[];
  };
};

export type EventListResponseDataItem = {
  id?: number;
  attributes?: Event;
};

export type EventListResponse = {
  data?: EventListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type Event = {
  /**
   * @pattern ^\d*$
   * @example 123456789
   */
  E_ID?: string;
  /**
   * @pattern ^\d*$
   * @example 123456789
   */
  eventId?: string;
  /**
   * @pattern ^\d*$
   * @example 123456789
   */
  terminId?: string;
  title?: string;
  description?: string;
  coords?: void;
  /**
   * @format date-time
   */
  startDate?: string;
  /**
   * @format date-time
   */
  endDate?: string;
  urls?: void;
  categories?: {
    data?: {
      id?: number;
      attributes?: {
        Name?: string;
        events?: {
          data?: {
            id?: number;
            attributes?: {
              /**
               * @pattern ^\d*$
               * @example 123456789
               */
              E_ID?: string;
              /**
               * @pattern ^\d*$
               * @example 123456789
               */
              eventId?: string;
              /**
               * @pattern ^\d*$
               * @example 123456789
               */
              terminId?: string;
              title?: string;
              description?: string;
              coords?: void;
              /**
               * @format date-time
               */
              startDate?: string;
              /**
               * @format date-time
               */
              endDate?: string;
              urls?: void;
              categories?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {
                    firstname?: string;
                    lastname?: string;
                    username?: string;
                    /**
                     * @format email
                     */
                    email?: string;
                    resetPasswordToken?: string;
                    registrationToken?: string;
                    isActive?: boolean;
                    roles?: {
                      data?: {
                        id?: number;
                        attributes?: {
                          name?: string;
                          code?: string;
                          description?: string;
                          users?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            }[];
                          };
                          permissions?: {
                            data?: {
                              id?: number;
                              attributes?: {
                                action?: string;
                                actionParameters?: void;
                                subject?: string;
                                properties?: void;
                                conditions?: void;
                                role?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                                /**
                                 * @format date-time
                                 */
                                createdAt?: string;
                                /**
                                 * @format date-time
                                 */
                                updatedAt?: string;
                                createdBy?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                                updatedBy?: {
                                  data?: {
                                    id?: number;
                                    attributes?: {};
                                  };
                                };
                              };
                            }[];
                          };
                          /**
                           * @format date-time
                           */
                          createdAt?: string;
                          /**
                           * @format date-time
                           */
                          updatedAt?: string;
                          createdBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          updatedBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                        };
                      }[];
                    };
                    blocked?: boolean;
                    preferedLanguage?: string;
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    }[];
  };
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
};

export type EventResponseDataObject = {
  id?: number;
  attributes?: Event;
};

export type EventResponse = {
  data?: EventResponseDataObject;
  meta?: Record<string, any>;
};

export type EventViewLocalizationRequest = {
  Title?: string;
  Description?: string;
  locale: string;
};

export type EventViewRequest = {
  data: {
    Title?: string;
    Description?: string;
    locale?: string;
  };
};

export type EventViewResponseDataObjectLocalized = {
  id?: number;
  attributes?: EventView;
};

export type EventViewLocalizationResponse = {
  data?: EventViewResponseDataObjectLocalized;
  meta?: Record<string, any>;
};

export type EventViewListResponseDataItemLocalized = {
  id?: number;
  attributes?: EventView;
};

export type EventViewLocalizationListResponse = {
  data?: EventViewListResponseDataItemLocalized[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type EventViewListResponseDataItem = {
  id?: number;
  attributes?: EventView;
};

export type EventViewListResponse = {
  data?: EventViewListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type EventView = {
  Title?: string;
  Description?: string;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {
        firstname?: string;
        lastname?: string;
        username?: string;
        /**
         * @format email
         */
        email?: string;
        resetPasswordToken?: string;
        registrationToken?: string;
        isActive?: boolean;
        roles?: {
          data?: {
            id?: number;
            attributes?: {
              name?: string;
              code?: string;
              description?: string;
              users?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              permissions?: {
                data?: {
                  id?: number;
                  attributes?: {
                    action?: string;
                    actionParameters?: void;
                    subject?: string;
                    properties?: void;
                    conditions?: void;
                    role?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        blocked?: boolean;
        preferedLanguage?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  localizations?: {
    data?: EventViewListResponseDataItemLocalized[];
  };
  locale?: string;
};

export type EventViewResponseDataObject = {
  id?: number;
  attributes?: EventView;
};

export type EventViewResponse = {
  data?: EventViewResponseDataObject;
  meta?: Record<string, any>;
};

export type HomeViewLocalizationRequest = {
  title: string;
  description?: string;
  tabs?: (number | string)[];
  locale: string;
};

export type HomeViewRequest = {
  data: {
    title: string;
    description?: string;
    tabs?: (number | string)[];
    locale?: string;
  };
};

export type HomeViewResponseDataObjectLocalized = {
  id?: number;
  attributes?: HomeView;
};

export type HomeViewLocalizationResponse = {
  data?: HomeViewResponseDataObjectLocalized;
  meta?: Record<string, any>;
};

export type HomeViewListResponseDataItemLocalized = {
  id?: number;
  attributes?: HomeView;
};

export type HomeViewLocalizationListResponse = {
  data?: HomeViewListResponseDataItemLocalized[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type HomeViewListResponseDataItem = {
  id?: number;
  attributes?: HomeView;
};

export type HomeViewListResponse = {
  data?: HomeViewListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type HomeView = {
  title: string;
  description?: string;
  tabs?: {
    data?: {
      id?: number;
      attributes?: {
        title?: string;
        cards?: {
          id?: number;
          __component?: string;
          imgSrc?: string;
          imgAlt?: string;
          title?: string;
          description?: string;
          button?: {
            id?: number;
            text?: string;
            url?: string;
            newTab?: boolean;
          };
        }[];
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        /**
         * @format date-time
         */
        publishedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {
              firstname?: string;
              lastname?: string;
              username?: string;
              /**
               * @format email
               */
              email?: string;
              resetPasswordToken?: string;
              registrationToken?: string;
              isActive?: boolean;
              roles?: {
                data?: {
                  id?: number;
                  attributes?: {
                    name?: string;
                    code?: string;
                    description?: string;
                    users?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      }[];
                    };
                    permissions?: {
                      data?: {
                        id?: number;
                        attributes?: {
                          action?: string;
                          actionParameters?: void;
                          subject?: string;
                          properties?: void;
                          conditions?: void;
                          role?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          /**
                           * @format date-time
                           */
                          createdAt?: string;
                          /**
                           * @format date-time
                           */
                          updatedAt?: string;
                          createdBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          updatedBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                        };
                      }[];
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              blocked?: boolean;
              preferedLanguage?: string;
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        localizations?: {
          data?: any[];
        };
        locale?: string;
      };
    }[];
  };
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  localizations?: {
    data?: HomeViewListResponseDataItemLocalized[];
  };
  locale?: string;
};

export type HomeViewResponseDataObject = {
  id?: number;
  attributes?: HomeView;
};

export type HomeViewResponse = {
  data?: HomeViewResponseDataObject;
  meta?: Record<string, any>;
};

export type OverviewTabLocalizationRequest = {
  title: string;
  cards?: CardsInformationCardVariant1Component[];
  locale: string;
};

export type OverviewTabRequest = {
  data: {
    title: string;
    cards?: CardsInformationCardVariant1Component[];
    locale?: string;
  };
};

export type OverviewTabResponseDataObjectLocalized = {
  id?: number;
  attributes?: OverviewTab;
};

export type OverviewTabLocalizationResponse = {
  data?: OverviewTabResponseDataObjectLocalized;
  meta?: Record<string, any>;
};

export type OverviewTabListResponseDataItemLocalized = {
  id?: number;
  attributes?: OverviewTab;
};

export type OverviewTabLocalizationListResponse = {
  data?: OverviewTabListResponseDataItemLocalized[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type OverviewTabListResponseDataItem = {
  id?: number;
  attributes?: OverviewTab;
};

export type OverviewTabListResponse = {
  data?: OverviewTabListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type OverviewTab = {
  title: string;
  cards?: CardsInformationCardVariant1Component[];
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {
        firstname?: string;
        lastname?: string;
        username?: string;
        /**
         * @format email
         */
        email?: string;
        resetPasswordToken?: string;
        registrationToken?: string;
        isActive?: boolean;
        roles?: {
          data?: {
            id?: number;
            attributes?: {
              name?: string;
              code?: string;
              description?: string;
              users?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              permissions?: {
                data?: {
                  id?: number;
                  attributes?: {
                    action?: string;
                    actionParameters?: void;
                    subject?: string;
                    properties?: void;
                    conditions?: void;
                    role?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        blocked?: boolean;
        preferedLanguage?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  localizations?: {
    data?: OverviewTabListResponseDataItemLocalized[];
  };
  locale?: string;
};

export type OverviewTabResponseDataObject = {
  id?: number;
  attributes?: OverviewTab;
};

export type OverviewTabResponse = {
  data?: OverviewTabResponseDataObject;
  meta?: Record<string, any>;
};

export type GenericButtonComponent = {
  id?: number;
  __component?: string;
  text?: string;
  url?: string;
  newTab?: boolean;
};

export type CardsInformationCardVariant1Component = {
  id?: number;
  __component?: string;
  imgSrc?: string;
  imgAlt?: string;
  title?: string;
  description?: string;
  button?: GenericButtonComponent;
};

export type ProjectRequest = {
  data: {
    title?: string;
    description?: string;
    fullText?: string;
    imageCaption?: string;
    imageUrl?: string;
    imageCredits?: string;
    projectId?: string;
  };
};

export type ProjectListResponseDataItem = {
  id?: number;
  attributes?: Project;
};

export type ProjectListResponse = {
  data?: ProjectListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type Project = {
  title?: string;
  description?: string;
  fullText?: string;
  imageCaption?: string;
  imageUrl?: string;
  imageCredits?: string;
  projectId?: string;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {
        firstname?: string;
        lastname?: string;
        username?: string;
        /**
         * @format email
         */
        email?: string;
        resetPasswordToken?: string;
        registrationToken?: string;
        isActive?: boolean;
        roles?: {
          data?: {
            id?: number;
            attributes?: {
              name?: string;
              code?: string;
              description?: string;
              users?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              permissions?: {
                data?: {
                  id?: number;
                  attributes?: {
                    action?: string;
                    actionParameters?: void;
                    subject?: string;
                    properties?: void;
                    conditions?: void;
                    role?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        blocked?: boolean;
        preferedLanguage?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
};

export type ProjectResponseDataObject = {
  id?: number;
  attributes?: Project;
};

export type ProjectResponse = {
  data?: ProjectResponseDataObject;
  meta?: Record<string, any>;
};

export type ProjectViewLocalizationRequest = {
  Title?: string;
  InfoFromAdmin?: GenericButtonComponent[];
  Description?: string;
  projects?: (number | string)[];
  locale: string;
};

export type ProjectViewRequest = {
  data: {
    Title?: string;
    InfoFromAdmin?: GenericButtonComponent[];
    Description?: string;
    projects?: (number | string)[];
    locale?: string;
  };
};

export type ProjectViewResponseDataObjectLocalized = {
  id?: number;
  attributes?: ProjectView;
};

export type ProjectViewLocalizationResponse = {
  data?: ProjectViewResponseDataObjectLocalized;
  meta?: Record<string, any>;
};

export type ProjectViewListResponseDataItemLocalized = {
  id?: number;
  attributes?: ProjectView;
};

export type ProjectViewLocalizationListResponse = {
  data?: ProjectViewListResponseDataItemLocalized[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type ProjectViewListResponseDataItem = {
  id?: number;
  attributes?: ProjectView;
};

export type ProjectViewListResponse = {
  data?: ProjectViewListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type ProjectView = {
  Title?: string;
  InfoFromAdmin?: GenericButtonComponent[];
  Description?: string;
  projects?: {
    data?: {
      id?: number;
      attributes?: {
        title?: string;
        description?: string;
        fullText?: string;
        imageCaption?: string;
        imageUrl?: string;
        imageCredits?: string;
        projectId?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        /**
         * @format date-time
         */
        publishedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {
              firstname?: string;
              lastname?: string;
              username?: string;
              /**
               * @format email
               */
              email?: string;
              resetPasswordToken?: string;
              registrationToken?: string;
              isActive?: boolean;
              roles?: {
                data?: {
                  id?: number;
                  attributes?: {
                    name?: string;
                    code?: string;
                    description?: string;
                    users?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      }[];
                    };
                    permissions?: {
                      data?: {
                        id?: number;
                        attributes?: {
                          action?: string;
                          actionParameters?: void;
                          subject?: string;
                          properties?: void;
                          conditions?: void;
                          role?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          /**
                           * @format date-time
                           */
                          createdAt?: string;
                          /**
                           * @format date-time
                           */
                          updatedAt?: string;
                          createdBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                          updatedBy?: {
                            data?: {
                              id?: number;
                              attributes?: {};
                            };
                          };
                        };
                      }[];
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              blocked?: boolean;
              preferedLanguage?: string;
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    }[];
  };
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
  localizations?: {
    data?: ProjectViewListResponseDataItemLocalized[];
  };
  locale?: string;
};

export type ProjectViewResponseDataObject = {
  id?: number;
  attributes?: ProjectView;
};

export type ProjectViewResponse = {
  data?: ProjectViewResponseDataObject;
  meta?: Record<string, any>;
};

export type ServiceRequest = {
  data: {
    services?: void;
  };
};

export type ServiceListResponseDataItem = {
  id?: number;
  attributes?: Service;
};

export type ServiceListResponse = {
  data?: ServiceListResponseDataItem[];
  meta?: {
    pagination?: {
      page?: number;
      /**
       * @minimum 25
       */
      pageSize?: number;
      /**
       * @maximum 1
       */
      pageCount?: number;
      total?: number;
    };
  };
};

export type Service = {
  services?: void;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
  /**
   * @format date-time
   */
  publishedAt?: string;
  createdBy?: {
    data?: {
      id?: number;
      attributes?: {
        firstname?: string;
        lastname?: string;
        username?: string;
        /**
         * @format email
         */
        email?: string;
        resetPasswordToken?: string;
        registrationToken?: string;
        isActive?: boolean;
        roles?: {
          data?: {
            id?: number;
            attributes?: {
              name?: string;
              code?: string;
              description?: string;
              users?: {
                data?: {
                  id?: number;
                  attributes?: {};
                }[];
              };
              permissions?: {
                data?: {
                  id?: number;
                  attributes?: {
                    action?: string;
                    actionParameters?: void;
                    subject?: string;
                    properties?: void;
                    conditions?: void;
                    role?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    /**
                     * @format date-time
                     */
                    createdAt?: string;
                    /**
                     * @format date-time
                     */
                    updatedAt?: string;
                    createdBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                    updatedBy?: {
                      data?: {
                        id?: number;
                        attributes?: {};
                      };
                    };
                  };
                }[];
              };
              /**
               * @format date-time
               */
              createdAt?: string;
              /**
               * @format date-time
               */
              updatedAt?: string;
              createdBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
              updatedBy?: {
                data?: {
                  id?: number;
                  attributes?: {};
                };
              };
            };
          }[];
        };
        blocked?: boolean;
        preferedLanguage?: string;
        /**
         * @format date-time
         */
        createdAt?: string;
        /**
         * @format date-time
         */
        updatedAt?: string;
        createdBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
        updatedBy?: {
          data?: {
            id?: number;
            attributes?: {};
          };
        };
      };
    };
  };
  updatedBy?: {
    data?: {
      id?: number;
      attributes?: {};
    };
  };
};

export type ServiceResponseDataObject = {
  id?: number;
  attributes?: Service;
};

export type ServiceResponse = {
  data?: ServiceResponseDataObject;
  meta?: Record<string, any>;
};

export type UploadFile = {
  id?: number;
  name?: string;
  alternativeText?: string;
  caption?: string;
  /**
   * @format integer
   */
  width?: number;
  /**
   * @format integer
   */
  height?: number;
  formats?: number;
  hash?: string;
  ext?: string;
  mime?: string;
  /**
   * @format double
   */
  size?: number;
  url?: string;
  previewUrl?: string;
  provider?: string;
  provider_metadata?: Record<string, any>;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
};

export type UsersPermissionsRole = {
  id?: number;
  name?: string;
  description?: string;
  type?: string;
  /**
   * @format date-time
   */
  createdAt?: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
};

export type UsersPermissionsUser = {
  /**
   * @example 1
   */
  id?: number;
  /**
   * @example foo.bar
   */
  username?: string;
  /**
   * @example foo.bar@strapi.io
   */
  email?: string;
  /**
   * @example local
   */
  provider?: string;
  /**
   * @example true
   */
  confirmed?: boolean;
  /**
   * @example false
   */
  blocked?: boolean;
  /**
   * @format date-time
   * @example 2022-06-02T08:32:06.258Z
   */
  createdAt?: string;
  /**
   * @format date-time
   * @example 2022-06-02T08:32:06.267Z
   */
  updatedAt?: string;
};

export type UsersPermissionsUserRegistration = {
  /**
   * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
   */
  jwt?: string;
  user?: UsersPermissionsUser;
};

export type UsersPermissionsPermissionsTree = {
  [key: string]: {
    /**
     * every controller of the api
     */
    controllers?: {
      [key: string]: {
        [key: string]: {
          enabled?: boolean;
          policy?: string;
        };
      };
    };
  };
};
